### ISSUE TITLE
custom server documents

### ISSUE THREAD

**Issue by dipenpatel235** [laike9m/VideoChat#1]
is there any steps to how to make complete it in own server
- own app arc server
- own wss server api
- allow more user instead of 2

**Comment by laike9m** [comment]
I don't work on this anymore. If I remember correctly, WebRTC does allow people to create their own server. I'm not sure how.

**Comment by dipenpatel235** [comment]
ok..no prolem...
can u please tell me suppose instead of 2 user view how can i do for multiple 5 user ?
Thanks

**Comment by laike9m** [comment]
I don't think it's possible, see
http://gingertech.net/2014/03/19/apprtc-googles-webrtc-test-app-and-its-parameters/
